### PR TITLE
Indent empty lines inside blocks

### LINKED ISSUE #77: cc doesn't auto-indent blank lines within a block
Test case: (`*` represents cursor position)
```
def a():
    b = 42
    c = "asdf"
*
    # random stuff
```

Pressing `cc` with `indentexpr=cindent(v:lnum)` gives the expected result:

```
def a():
    b = 42
    c = "asdf"
    *
    # random stuff
```

With `indentexpr=GetPythonPEPIndent(v:lnum)` however, the cursor remains on column 1:

```
def a():
    b = 42
    c = "asdf"
*
    # random stuff
```

### PR DESCRIPTION
**Pull request by aldanor**
Fixes #77.

(I couldn't make the tests run on Mac through mvim, so I hope they will pass on Travis; vimrunner is quite flaky, Vader could have been much better...)

### CODE REVIEW

**Comment by aldanor** [comment]
@blueyed Looks all green.

**Comment by aldanor** [comment]
What would you expect in this case?

```python
if a:
    if b:
        pass
*
    pass
```

At cursor (`*`) press `cc`, should it indent 4 or 8?

**Comment by aldanor** [comment]
Ok; done, I think.

**Comment by blueyed** [comment]
Thank you, pushed some minor fixups.

**Comment by blueyed** [comment]
Looks fine, will merge it when it is green still.

> Vader could have been much better

Yes, it wasn't my choice, and I would go with Vader currently myself.
Maybe it could be used for new tests..

**Comment by blueyed** [comment]
Thank you very much!

**Comment by aldanor** [comment]
Cheers, glad to help :)

**Pull request merged**
